name: "Placeholder name"
description: "Placeholder description"

inputs: {}

outputs:
  next-version:
    description: "Placeholder description"

runs:
  using: "docker"
  image: "Dockerfile" # Builds the Dockerfile in this directory
