name: Secrets stage

on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: "Reference used on checkout code"
      repo:
        type: string
        required: true
        description: "Repository used on checkout code"

jobs:
  secret-detection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important: Gitleaks needs history to scan commits
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repo }}
      - name: Catch-up with changes in default branch
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          # Ensure we are in the git root
          if [ ! -d .git ]; then
            echo "Current directory: $(pwd)"
            echo "Contents: $(ls -A)"
            echo "❌ Error: .git directory not found. Did checkout succeed?"
            exit 1
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Pull with rebase
          git pull origin ${{ inputs.target_branch || 'main' }} --rebase
      - name: Secrets | secret_detection (1/2)
        id: secret_detection
        uses: open-appdev-lab/ansible-collections-ci/.github/actions/secret-detection@main
      - name: Secrets | secret_detection (2/2)
        uses: actions/upload-artifact@v4
        if: always() && steps.secret_detection.outcome != 'skipped'
        with:
          name: secret_detection
          path: secret-detection-report.json
          if-no-files-found: error